apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-pipeline
  labels:
    app: devops-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-pipeline
  template:
    metadata:
      labels:
        app: devops-pipeline
    spec:
      containers:
      - name: devops-pipeline
        image: devops-pipeline:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
